### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method getAllApps on channel launcher_assist)

### ISSUE THREAD

**Issue by emvaized** [hathibelagal-dev/launcher-assist-for-flutter#10]
Using version `1.1.3`, this error occures when trying to call `LauncherAssist.getAllApps()` in initState() the same way as in README's example.

```
E/flutter (11054): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getAllApps on channel launcher_assist)
E/flutter (11054): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
E/flutter (11054): <asynchronous suspension>
E/flutter (11054): #1      LauncherAssist.getAllApps (package:launcher_assist/launcher_assist.dart:8:31)
...
```

**Comment by emvaized** [comment]
Just had to rerun the whole app. Issue closed.
